run:
  timeout: 10m
  go: 1.18

linters:
  disable-all: true
  enable:
    # Enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

output:
  print-issued-lines: true
  sort-results: true
