version: "2"
linters:
  default: all
  disable:
    - canonicalheader
    - contextcheck
    - copyloopvar
    - cyclop
    - depguard
    - dupl
    - exhaustruct
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - gosec
    - intrange
    - ireturn
    - lll
    - maintidx
    - mnd
    - musttag
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - perfsprint
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - testpackage
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
  settings:
    gomoddirectives:
      replace-allow-list:
        - github.com/attestantio/go-builder-client
        - github.com/attestantio/go-eth2-client
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
