linters:
  enable-all: true
  disable:
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - gomnd
    - lll
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - musttag

    #
    # Maybe fix later:
    #
    - cyclop
    - gocognit
    - goconst
    - gosec
    - ireturn
    - noctx
    - tagliatelle

    #
    # Disabled because of generics:
    #
    - contextcheck
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign

    #
    # Disabled because deprecated:
    #
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - scopelint
    - varcheck

linters-settings:
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  gomoddirectives:
     replace-allow-list:
      # TODO: remove when https://github.com/attestantio/go-builder-client/pull/13 is merged
      - github.com/attestantio/go-builder-client

output:
  print-issued-lines: true
  sort-results: true
