# https://goreleaser.com/customization/release/
builds:
  - skip: true
release:
  draft: true
  extra_files:
    - glob: ./build/*
  header: |
    # 🚀 Features
    # 🎄 Enhancements
    # 🐞 Notable bug fixes
    # 🎠 Community
