// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*executionPayloadMarshallingOverrides)(nil)

// MarshalJSON marshals as JSON.
func (e ExecutionPayloadHeaderV1) MarshalJSON() ([]byte, error) {
	type ExecutionPayloadHeaderV1 struct {
		ParentHash       common.Hash    `json:"parentHash" gencodec:"required"`
		FeeRecipient     common.Address `json:"feeRecipient" gencodec:"required"`
		StateRoot        common.Hash    `json:"stateRoot" gencodec:"required"`
		ReceiptsRoot     common.Hash    `json:"receiptsRoot" gencodec:"required"`
		LogsBloom        hexutil.Bytes  `json:"logsBloom" gencodec:"required"`
		PrevRandao       common.Hash    `json:"prevRandao" gencodec:"required"`
		BlockNumber      hexutil.Uint64 `json:"blockNumber" gencodec:"required"`
		GasLimit         hexutil.Uint64 `json:"gasLimit" gencodec:"required"`
		GasUsed          hexutil.Uint64 `json:"gasUsed" gencodec:"required"`
		Timestamp        hexutil.Uint64 `json:"timestamp" gencodec:"required"`
		ExtraData        hexutil.Bytes  `json:"extraData" gencodec:"required"`
		BaseFeePerGas    *hexutil.Big   `json:"baseFeePerGas" gencodec:"required"`
		BlockHash        common.Hash    `json:"blockHash" gencodec:"required"`
		TransactionsRoot common.Hash    `json:"transactionsRoot" gencodec:"required"`
	}
	var enc ExecutionPayloadHeaderV1
	enc.ParentHash = e.ParentHash
	enc.FeeRecipient = e.FeeRecipient
	enc.StateRoot = e.StateRoot
	enc.ReceiptsRoot = e.ReceiptsRoot
	enc.LogsBloom = e.LogsBloom
	enc.PrevRandao = e.PrevRandao
	enc.BlockNumber = hexutil.Uint64(e.BlockNumber)
	enc.GasLimit = hexutil.Uint64(e.GasLimit)
	enc.GasUsed = hexutil.Uint64(e.GasUsed)
	enc.Timestamp = hexutil.Uint64(e.Timestamp)
	enc.ExtraData = e.ExtraData
	enc.BaseFeePerGas = (*hexutil.Big)(e.BaseFeePerGas)
	enc.BlockHash = e.BlockHash
	enc.TransactionsRoot = e.TransactionsRoot
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (e *ExecutionPayloadHeaderV1) UnmarshalJSON(input []byte) error {
	type ExecutionPayloadHeaderV1 struct {
		ParentHash       *common.Hash    `json:"parentHash" gencodec:"required"`
		FeeRecipient     *common.Address `json:"feeRecipient" gencodec:"required"`
		StateRoot        *common.Hash    `json:"stateRoot" gencodec:"required"`
		ReceiptsRoot     *common.Hash    `json:"receiptsRoot" gencodec:"required"`
		LogsBloom        *hexutil.Bytes  `json:"logsBloom" gencodec:"required"`
		PrevRandao       *common.Hash    `json:"prevRandao" gencodec:"required"`
		BlockNumber      *hexutil.Uint64 `json:"blockNumber" gencodec:"required"`
		GasLimit         *hexutil.Uint64 `json:"gasLimit" gencodec:"required"`
		GasUsed          *hexutil.Uint64 `json:"gasUsed" gencodec:"required"`
		Timestamp        *hexutil.Uint64 `json:"timestamp" gencodec:"required"`
		ExtraData        *hexutil.Bytes  `json:"extraData" gencodec:"required"`
		BaseFeePerGas    *hexutil.Big    `json:"baseFeePerGas" gencodec:"required"`
		BlockHash        *common.Hash    `json:"blockHash" gencodec:"required"`
		TransactionsRoot *common.Hash    `json:"transactionsRoot" gencodec:"required"`
	}
	var dec ExecutionPayloadHeaderV1
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.ParentHash == nil {
		return errors.New("missing required field 'parentHash' for ExecutionPayloadHeaderV1")
	}
	e.ParentHash = *dec.ParentHash
	if dec.FeeRecipient == nil {
		return errors.New("missing required field 'feeRecipient' for ExecutionPayloadHeaderV1")
	}
	e.FeeRecipient = *dec.FeeRecipient
	if dec.StateRoot == nil {
		return errors.New("missing required field 'stateRoot' for ExecutionPayloadHeaderV1")
	}
	e.StateRoot = *dec.StateRoot
	if dec.ReceiptsRoot == nil {
		return errors.New("missing required field 'receiptsRoot' for ExecutionPayloadHeaderV1")
	}
	e.ReceiptsRoot = *dec.ReceiptsRoot
	if dec.LogsBloom == nil {
		return errors.New("missing required field 'logsBloom' for ExecutionPayloadHeaderV1")
	}
	e.LogsBloom = *dec.LogsBloom
	if dec.PrevRandao == nil {
		return errors.New("missing required field 'prevRandao' for ExecutionPayloadHeaderV1")
	}
	e.PrevRandao = *dec.PrevRandao
	if dec.BlockNumber == nil {
		return errors.New("missing required field 'blockNumber' for ExecutionPayloadHeaderV1")
	}
	e.BlockNumber = uint64(*dec.BlockNumber)
	if dec.GasLimit == nil {
		return errors.New("missing required field 'gasLimit' for ExecutionPayloadHeaderV1")
	}
	e.GasLimit = uint64(*dec.GasLimit)
	if dec.GasUsed == nil {
		return errors.New("missing required field 'gasUsed' for ExecutionPayloadHeaderV1")
	}
	e.GasUsed = uint64(*dec.GasUsed)
	if dec.Timestamp == nil {
		return errors.New("missing required field 'timestamp' for ExecutionPayloadHeaderV1")
	}
	e.Timestamp = uint64(*dec.Timestamp)
	if dec.ExtraData == nil {
		return errors.New("missing required field 'extraData' for ExecutionPayloadHeaderV1")
	}
	e.ExtraData = *dec.ExtraData
	if dec.BaseFeePerGas == nil {
		return errors.New("missing required field 'baseFeePerGas' for ExecutionPayloadHeaderV1")
	}
	e.BaseFeePerGas = (*big.Int)(dec.BaseFeePerGas)
	if dec.BlockHash == nil {
		return errors.New("missing required field 'blockHash' for ExecutionPayloadHeaderV1")
	}
	e.BlockHash = *dec.BlockHash
	if dec.TransactionsRoot == nil {
		return errors.New("missing required field 'transactionsRoot' for ExecutionPayloadHeaderV1")
	}
	e.TransactionsRoot = *dec.TransactionsRoot
	return nil
}
