// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package lib

import (
	"encoding/json"
	"errors"

	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*getHeaderResponseMarshallingOverrides)(nil)

// MarshalJSON marshals as JSON.
func (g GetHeaderResponse) MarshalJSON() ([]byte, error) {
	type GetHeaderResponse struct {
		Message   GetHeaderResponseMessage `json:"message" gencodec:"required"`
		PublicKey hexutil.Bytes            `json:"publicKey" gencodec:"required"`
		Signature hexutil.Bytes            `json:"signature" gencodec:"required"`
	}
	var enc GetHeaderResponse
	enc.Message = g.Message
	enc.PublicKey = g.PublicKey
	enc.Signature = g.Signature
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (g *GetHeaderResponse) UnmarshalJSON(input []byte) error {
	type GetHeaderResponse struct {
		Message   *GetHeaderResponseMessage `json:"message" gencodec:"required"`
		PublicKey *hexutil.Bytes            `json:"publicKey" gencodec:"required"`
		Signature *hexutil.Bytes            `json:"signature" gencodec:"required"`
	}
	var dec GetHeaderResponse
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Message == nil {
		return errors.New("missing required field 'message' for GetHeaderResponse")
	}
	g.Message = *dec.Message
	if dec.PublicKey == nil {
		return errors.New("missing required field 'publicKey' for GetHeaderResponse")
	}
	g.PublicKey = *dec.PublicKey
	if dec.Signature == nil {
		return errors.New("missing required field 'signature' for GetHeaderResponse")
	}
	g.Signature = *dec.Signature
	return nil
}
