name: Go

on:
  push:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: make test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install revive linter
        run: go install github.com/mgechev/revive@v1.1.3

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.2.2

      - name: Lint
        run: make lint

  mergemock:
    name: Mergemock
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build mev-boost
        run: make build

      - name: Check out the mergemock code repo
        uses: actions/checkout@v2
        with:
          repository: flashbots/mergemock
          path: mergemock

      - name: Download mergemock genesis.json
        run: cd mergemock && wget https://gist.githubusercontent.com/lightclient/799c727e826483a2804fc5013d0d3e3d/raw/2e8824fa8d9d9b040f351b86b75c66868fb9b115/genesis.json

      - name: Build mergemock
        run: cd mergemock && go build . mergemock

      - name: Run mergemock consensus tests
        run: |
          make MERGEMOCK_DIR=./mergemock run-mergemock-engine &
          make run-boost-with-mergemock &
          sleep 5
          make MERGEMOCK_DIR=./mergemock run-mergemock-consensus
