name: Linting

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.22.0
          id: go

      - name: Ensure go mod tidy runs without changes
        run: |
          go mod tidy
          git diff-index HEAD
          git diff-index --quiet HEAD

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@v0.6.0

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.4.7

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.1

      - name: Lint
        run: make lint
