name: Linting

on:
  push:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          id: go

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49
          args: --config=.golangci.yml --out-${NO_FUTURE}format colored-line-number
