name: Publish Docker Image

on:
  push:
    branches:
      - feat/dynamic-relay-configuration

permissions:
  contents: write

jobs:
  docker-image:
    name: Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Get tag version
        run: | 
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "SHORT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Print version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo $SHORT_COMMIT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push portable
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ env.RELEASE_VERSION }}
            CGO_CFLAGS=-O -D__BLST_PORTABLE__
          platforms: linux/amd64,linux/arm64
          tags: happygopher/mev-boost-dev:${{ env.SHORT_COMMIT}},happygopher/mev-boost-dev:latest
